trigger: 
 branches:
  include:
    - main
pool: $(agentpool)
variables:
- name: agentpool
  value: war-agent
parameters:
- name: environment
  displayName: select environment
  values:
    - dev
    - UAT
    - prod
  default: dev
- name: runapply
  displayName: Run Apply?
  type: boolean
  default: false
stages:
- stage: buildstage
  displayName: Build stage
  jobs:
  - job: terraforminstall
    steps:
    - task: TerraformInstaller@1
      displayName: terraform installer
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'''
        backendServiceArm: 'applesc'
        backendAzureRmOverrideSubscriptionID: 'ca0e89ec-4b6f-43aa-93b2-058a2da5be0d'
        backendAzureRmResourceGroupName: 'edfusion-rg'
        backendAzureRmStorageAccountName: 'stg1983'
        backendAzureRmContainerName: 'container'
        backendAzureRmKey: 'dev.terraform.tfstate'
    - task: TerraformTask@5
      displayName: terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'''
    - task: TerraformTask@5
      displayName: terraform plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceNameAzureRM: 'applesc'
        environmentAzureRmOverrideSubscriptionID: 'ca0e89ec-4b6f-43aa-93b2-058a2da5be0d'
